version: '3.8'

services:
  web:
    build: .
    container_name: video_combiner
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /app/node_modules
      - /app/theme/node_modules
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    command: >
      bash -c "python manage.py migrate &&
               python manage.py tailwind install &&
               python manage.py tailwind build &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume: